# turn 0

turn_0 = {
   "game":{
      "id":"5aa09d22-e49d-4b06-be89-d871735a0882"
   },
   "turn":0,
   "board":{
      "height":11,
      "width":11,
      "food":[
         {
            "x":4,
            "y":4
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":0,
            "y":8
         }
      ],
      "snakes":[
         {
            "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
            "name":"hansy-snake",
            "health":100,
            "body":[
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               }
            ],
            "shout":""
         },
         {
            "id":"gs_XXKWYSRRMxhvBgwg4DJXw6yD",
            "name":"Derpy Snake",
            "health":100,
            "body":[
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               }
            ],
            "shout":""
         },
         {
            "id":"gs_T8gwyXPQVXgD4hfQgd778PKc",
            "name":"SnakeBot.exe",
            "health":100,
            "body":[
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               }
            ],
            "shout":""
         }
      ]
   },
   "you":{
      "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
      "name":"hansy-snake",
      "health":100,
      "body":[
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         }
      ],
      "shout":""
   }
}

turn_1 = {
   "game":{
      "id":"5aa09d22-e49d-4b06-be89-d871735a0882"
   },
   "turn":1,
   "board":{
      "height":11,
      "width":11,
      "food":[
         {
            "x":4,
            "y":4
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":0,
            "y":8
         }
      ],
      "snakes":[
         {
            "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
            "name":"hansy-snake",
            "health":99,
            "body":[
               {
                  "x":9,
                  "y":0
               },
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               }
            ],
            "shout":""
         },
         {
            "id":"gs_XXKWYSRRMxhvBgwg4DJXw6yD",
            "name":"Derpy Snake",
            "health":99,
            "body":[
               {
                  "x":1,
                  "y":8
               },
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               }
            ],
            "shout":""
         },
         {
            "id":"gs_T8gwyXPQVXgD4hfQgd778PKc",
            "name":"SnakeBot.exe",
            "health":99,
            "body":[
               {
                  "x":5,
                  "y":8
               },
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               }
            ],
            "shout":""
         }
      ]
   },
   "you":{
      "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
      "name":"hansy-snake",
      "health":99,
      "body":[
         {
            "x":9,
            "y":0
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         }
      ],
      "shout":""
   }
}

turn_3 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 112, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 82, 'body': [{'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 9, 'y': 4}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 84, 'body': [{'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 84, 'body': [{'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'shout': ''}}

turn_4 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 114, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 80, 'body': [{'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 82, 'body': [{'x': 8, 'y': 2}, {'x': 9, 'y': 2}, {'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 82, 'body': [{'x': 8, 'y': 2}, {'x': 9, 'y': 2}, {'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}], 'shout': ''}}

turn_5 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 110, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 84, 'body': [{'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 86, 'body': [{'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 86, 'body': [{'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}], 'shout': ''}}
