# turn 0

turn_0 = {
   "game":{
      "id":"5aa09d22-e49d-4b06-be89-d871735a0882"
   },
   "turn":0,
   "board":{
      "height":11,
      "width":11,
      "food":[
         {
            "x":4,
            "y":4
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":0,
            "y":8
         }
      ],
      "snakes":[
         {
            "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
            "name":"hansy-snake",
            "health":100,
            "body":[
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               }
            ],
            "shout":""
         },
         {
            "id":"gs_XXKWYSRRMxhvBgwg4DJXw6yD",
            "name":"Derpy Snake",
            "health":100,
            "body":[
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               }
            ],
            "shout":""
         },
         {
            "id":"gs_T8gwyXPQVXgD4hfQgd778PKc",
            "name":"SnakeBot.exe",
            "health":100,
            "body":[
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               }
            ],
            "shout":""
         }
      ]
   },
   "you":{
      "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
      "name":"hansy-snake",
      "health":100,
      "body":[
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         }
      ],
      "shout":""
   }
}

turn_1 = {
   "game":{
      "id":"5aa09d22-e49d-4b06-be89-d871735a0882"
   },
   "turn":1,
   "board":{
      "height":11,
      "width":11,
      "food":[
         {
            "x":4,
            "y":4
         },
         {
            "x":4,
            "y":1
         },
         {
            "x":0,
            "y":8
         }
      ],
      "snakes":[
         {
            "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
            "name":"hansy-snake",
            "health":99,
            "body":[
               {
                  "x":9,
                  "y":0
               },
               {
                  "x":9,
                  "y":1
               },
               {
                  "x":9,
                  "y":1
               }
            ],
            "shout":""
         },
         {
            "id":"gs_XXKWYSRRMxhvBgwg4DJXw6yD",
            "name":"Derpy Snake",
            "health":99,
            "body":[
               {
                  "x":1,
                  "y":8
               },
               {
                  "x":1,
                  "y":9
               },
               {
                  "x":1,
                  "y":9
               }
            ],
            "shout":""
         },
         {
            "id":"gs_T8gwyXPQVXgD4hfQgd778PKc",
            "name":"SnakeBot.exe",
            "health":99,
            "body":[
               {
                  "x":5,
                  "y":8
               },
               {
                  "x":5,
                  "y":9
               },
               {
                  "x":5,
                  "y":9
               }
            ],
            "shout":""
         }
      ]
   },
   "you":{
      "id":"gs_DX78Q4VWYjSMfbHh4T4dByDM",
      "name":"hansy-snake",
      "health":99,
      "body":[
         {
            "x":9,
            "y":0
         },
         {
            "x":9,
            "y":1
         },
         {
            "x":9,
            "y":1
         }
      ],
      "shout":""
   }
}

turn_3 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 112, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 82, 'body': [{'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 9, 'y': 4}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 84, 'body': [{'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 84, 'body': [{'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'shout': ''}}

turn_4 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 114, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 80, 'body': [{'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 82, 'body': [{'x': 8, 'y': 2}, {'x': 9, 'y': 2}, {'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 82, 'body': [{'x': 8, 'y': 2}, {'x': 9, 'y': 2}, {'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}], 'shout': ''}}

turn_5 = {'game': {'id': '29e10ae1-ffcf-4057-a30f-a8ea4e091292'}, 'turn': 110, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 0}, {'x': 1, 'y': 3}, {'x': 0, 'y': 2}], 'snakes': [{'id': 'gs_hHFhpc3cPP4pXyhPQBjYBpy3', 'name': 'Rubelliguis', 'health': 84, 'body': [{'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}], 'shout': "I am Kai's snake!"}, {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 86, 'body': [{'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}], 'shout': ''}]}, 'you': {'id': 'gs_gwdvDGxtWkhQtFcDR9BbT9PQ', 'name': 'snaky', 'health': 86, 'body': [{'x': 10, 'y': 0}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}], 'shout': ''}}

turn_path = {'game': {'id': '4d0b5b22-8e77-4e1d-bc79-59d890c8c2e3'}, 'turn': 173, 'board': {'height': 11, 'width': 11, 'food': [{'x': 0, 'y': 9}, {'x': 8, 'y': 7}, {'x': 4, 'y': 2}], 'snakes': [{'id': 'gs_rTg9RMvSmYWVRvKwbXySCDk4', 'name': 'snacky', 'health': 98, 'body': [{'x': 4, 'y': 3}, {'x': 4, 'y': 4}, {'x': 5, 'y': 4}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 4, 'y': 6}, {'x': 3, 'y': 6}, {'x': 3, 'y': 7}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}], 'shout': ''}, {'id': 'gs_j8bXKbqF3yrvcybhVvkXffrd', 'name': 'SSR Snake', 'health': 100, 'body': [{'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 0, 'y': 3}, {'x': 0, 'y': 2}, {'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 8, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 6}], 'shout': ''}]}, 'you': {'id': 'gs_rTg9RMvSmYWVRvKwbXySCDk4', 'name': 'snacky', 'health': 98, 'body': [{'x': 4, 'y': 3}, {'x': 4, 'y': 4}, {'x': 5, 'y': 4}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 4, 'y': 6}, {'x': 3, 'y': 6}, {'x': 3, 'y': 7}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}], 'shout': ''}}

turn_path_2 = {'game': {'id': '7fc0adec-01c2-454b-a14f-1ff031f365ae'}, 'turn': 127, 'board': {'height': 11, 'width': 11, 'food': [{'x': 10, 'y': 5}, {'x': 8, 'y': 0}, {'x': 10, 'y': 0}, {'x': 6, 'y': 0}], 'snakes': [{'id': 'gs_49WgFS4fcmBf34xKShSdTpJR', 'name': 'snacky', 'health': 99, 'body': [{'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 3, 'y': 8}], 'shout': ''}, {'id': 'gs_x8CtdKhvb3jXGWY63QgHCftM', 'name': 'GoPofAdder', 'health': 93, 'body': [{'x': 4, 'y': 7}, {'x': 3, 'y': 7}, {'x': 2, 'y': 7}, {'x': 1, 'y': 7}, {'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 2, 'y': 6}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}], 'shout': ''}, {'id': 'gs_43PbkSyHHkKgKXR86GqG8PPK', 'name': 'snake-2020', 'health': 72, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 7, 'y': 9}, {'x': 8, 'y': 9}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}], 'shout': ''}]}, 'you': {'id': 'gs_49WgFS4fcmBf34xKShSdTpJR', 'name': 'snacky', 'health': 99, 'body': [{'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 3, 'y': 8}], 'shout': ''}}


turn_no_path = {'game': {'id': 'dc39570f-13de-4237-bb90-142323057cbc'}, 'turn': 177, 'board': {'height': 11, 'width': 11, 'food': [{'x': 10, 'y': 6}, {'x': 7, 'y': 3}, {'x': 10, 'y': 5}], 'snakes': [{'id': 'gs_b4dGrmYYyM6f34G8F6YcY6TP', 'name': 'snacky', 'health': 99, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 6, 'y': 7}, {'x': 6, 'y': 8}, {'x': 6, 'y': 9}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 4, 'y': 10}, {'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 0, 'y': 10}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}], 'shout': ''}, {'id': 'gs_kwmtYDKtgCMddJpBrJQJ748G', 'name': 'HamSnake', 'health': 90, 'body': [{'x': 8, 'y': 1}, {'x': 7, 'y': 1}, {'x': 6, 'y': 1}, {'x': 5, 'y': 1}, {'x': 4, 'y': 1}, {'x': 3, 'y': 1}, {'x': 2, 'y': 1}, {'x': 1, 'y': 1}, {'x': 0, 'y': 1}, {'x': 0, 'y': 0}, {'x': 1, 'y': 0}, {'x': 2, 'y': 0}], 'shout': ''}]}, 'you': {'id': 'gs_b4dGrmYYyM6f34G8F6YcY6TP', 'name': 'snacky', 'health': 99, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 6, 'y': 7}, {'x': 6, 'y': 8}, {'x': 6, 'y': 9}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 4, 'y': 10}, {'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 0, 'y': 10}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}], 'shout': ''}}

turn_no_path_2 = {'game': {'id': '263c1dbb-b591-4222-a4b3-b09594e90480'}, 'turn': 299, 'board': {'height': 11, 'width': 11, 'food': [{'x': 1, 'y': 10}, {'x': 0, 'y': 9}, {'x': 2, 'y': 4}, {'x': 2, 'y': 8}], 'snakes': [{'id': 'gs_gckJbG3tKgpXRfxWVWdKWBYb', 'name': 'snacky', 'health': 94, 'body': [{'x': 6, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 3, 'y': 1}, {'x': 2, 'y': 1}, {'x': 1, 'y': 1}, {'x': 1, 'y': 2}, {'x': 0, 'y': 2}, {'x': 0, 'y': 3}, {'x': 0, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 2, 'y': 6}, {'x': 1, 'y': 6}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 1, 'y': 7}], 'shout': ''}, {'id': 'gs_6PwFyvbbrKKfyrSjc3T6RMJH', 'name': 'DSnek', 'health': 63, 'body': [{'x': 7, 'y': 2}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 7, 'y': 4}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 4}, {'x': 10, 'y': 3}, {'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 1}, {'x': 9, 'y': 1}], 'shout': 'Organizational culture brings both pleasure and pain.'}]}, 'you': {'id': 'gs_gckJbG3tKgpXRfxWVWdKWBYb', 'name': 'snacky', 'health': 94, 'body': [{'x': 6, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 3, 'y': 1}, {'x': 2, 'y': 1}, {'x': 1, 'y': 1}, {'x': 1, 'y': 2}, {'x': 0, 'y': 2}, {'x': 0, 'y': 3}, {'x': 0, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 2, 'y': 6}, {'x': 1, 'y': 6}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 1, 'y': 7}], 'shout': ''}}
